### ISSUE TITLE
Increasing maximum number face count to 5000

### ISSUE THREAD

**Issue by gavinleong** [iMoonLab/MeshNet#12]
Hi, thank you for providing the code to your MeshNet paper. I have been exploring the use of more detailed meshes and how well MeshNet performs when using meshes with maximum face count of 5000. 

Currently, I am using MeshNet to distinguish between 2 categories of meshes that have been created using structure from motion photogrammetry: meshes that have carvings, and meshes that do not have carvings. Since the subject matter is of faint prehistoric carvings on stones, I believe I need to increase the face count to improve the amount of detail given to MeshNet. 

Do you have any advice on what I should do, such as changing parameters or some of your code to improve the accuracy of training and testing of these 5k face meshes? Currently, the accuracy I am getting when applying MeshNet to my data is very low. I am rather new to neural networks.

I have attached an example of a carving and an example of areas without carvings (flat).

[carving_meshes.zip](https://github.com/iMoonLab/MeshNet/files/3800693/carving_meshes.zip)

Thank you for your help!

**Comment by thss15fyt** [comment]
Thanks for your interest on our work!

I have seen the provided examples and the difference between two categories seems to be quite small, making it a difficult task. MeshNet may not be suitable for this task, since it focus on the obvious structural features of models. In my opinion, you could try some methods from computer graphics, such as curvature calculation, or get the 2D depth map for classification, which may be better for capturing the slight changes of the surface.

**Comment by thss15fyt** [comment]
The visulization of curvature:

![批注 2019-11-11 164621](https://user-images.githubusercontent.com/19227233/68573911-bcaf3200-04a3-11ea-98af-266686bdb142.png)
