### ISSUE TITLE
Can this method be used for model segmentation?

### ISSUE THREAD

**Issue by duhau** [iMoonLab/MeshNet#15]
I want to know whether this method can be used for model segmentation， if so, how should I prepare for input dates.

**Comment by thss15fyt** [comment]
Thanks for your interest on our work and sorry for the late reply.

We think it is possible to adapt MeshNet for segmentation task as classification on each face, since we extract semantic features of faces in the model classification task. Roughly speaking, you should prepare segmentation labels for mesh faces, and conduct the similar preprocessing that similifies mesh models and reorganizes the data format. Then modify the network architecture, remove the global pooling and apply an classification module to face features. 

You may reference the following paper that adapting MeshNet to medical data segmentations: MeshSNet: Deep Multi-scale Mesh Feature Learning for End-to-End Tooth Labeling on 3D Dental Surfaces.
