### ISSUE TITLE
one face can have more than 3 connections

### ISSUE THREAD

**Issue by tranduytrung** [iMoonLab/MeshNet#3]
Hi, I am confused with the statement: "one triangular face can connect with no more than three faces". In 3 dimensional space, an edge could be shared with more than 3 triangles. In fact, in your processed MeshNet40, takes /lamp/test/lamp_0139.npz for example, the `neighbor_index[0]` has 3 corresponding to 3 neighbor faces (1,   9, 100). In the other hand, in `neighbor_index[11]` is (10,  0, 14) containing 0. So, the face 0 has at least 4 neighbors including 11.

![](https://i.ibb.co/qpNCZqM/Capture.png)

Could you please confirm it and how did you choose the neighbors in that case?

**Comment by thss15fyt** [comment]
Hi, thanks for your attention to our work.
There do exist some bad cases as your described in our processed dataset. It is because the simplification method we used is not quite satisfying when we force the number of faces to be less than 1024. In current codes, we choose the first three faces appearing in the `.off` files.
We will make a count on the number of bad cases in our simplified dataset. And we are also looking for a better preprocessing method to do this work.
